# Generated by Django 4.2 on 2023-07-24 17:36

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auther',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_profile', models.ImageField(upload_to='doctor')),
                ('name', models.CharField(max_length=100, null=True)),
                ('about_doctor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetured_image', models.ImageField(upload_to='Image')),
                ('title', models.CharField(max_length=200)),
                ('hindi_title', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('hindi_description', models.CharField(max_length=250)),
                ('content', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], max_length=100)),
                ('section', models.CharField(choices=[('Main_post', 'Main_post'), ('Popular', 'Popular'), ('Recent', 'Recent'), ('Editors_Pick', 'Editors_Pick'), ('Trending', 'Trending'), ('Inspiration', 'Inspiration'), ('Latest_Post', 'Latest_Post')], max_length=200)),
                ('main_post', models.BooleanField(default=False)),
                ('Popular', models.BooleanField(default=False)),
                ('Recent', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.auther')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_category')),
                ('tag', models.ManyToManyField(to='blog.tag')),
            ],
            options={
                'db_table': 'blog_Post',
            },
        ),
    ]
