# Generated by Django 4.2 on 2023-07-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='img',
            field=models.ImageField(upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='image',
            field=models.ImageField(upload_to='brand/'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(null=True, upload_to='product/'),
        ),
    ]
